apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      service: http-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: http-server
    spec:
      containers:
      - name: sellingpoint
        image: 172.16.238.15:5000/selling-point-service-v1.0:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-svc
spec:
  selector:
    service: http-server
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
